# 第三章：用python进行数据分析

In [2]:
import numpy as np
import pandas as pd
import scipy as sp

# 设置浮点数打印精度为3位小数
%precision 3

'%.3f'

In [4]:
fish_multi = pd.read_csv("3-2-1-fish_multi.csv")
fish_multi

species  length
0       A       2
1       A       3
2       A       4
3       B       6
4       B       8
5       B      10

In [5]:
group = fish_multi.groupby("species")
group.mean()

length
species        
A           3.0
B           8.0

In [6]:
group.std(ddof=1)

length
species        
A           1.0
B           2.0

In [7]:
group.describe()

length                                    
         count mean  std  min  25%  50%  75%   max
species                                           
A          3.0  3.0  1.0  2.0  2.5  3.0  3.5   4.0
B          3.0  8.0  2.0  6.0  7.0  8.0  9.0  10.0

## 列联表

In [8]:
shoes = pd.read_csv("3-2-2-shoes.csv")
shoes

store color  sales
0  tokyo  blue     10
1  tokyo   red     15
2  osaka  blue     13
3  osaka   red      9

In [9]:
cross = pd.pivot_table(
    data=shoes,
    values="sales",
    aggfunc="sum",
    index="store",
    columns="color"
)
cross

color  blue  red
store           
osaka    13    9
tokyo    10   15

## 协方差

1. 协方差大于0：随着x增大，y也增大
1. 协方差小于0：随着x增大，y减小
1. 协方差等于0：两个变量不相关

## 协方差矩阵

[sigma_x_2, cov(x, y)]

[cov(x, y), sigma_y_2]

In [10]:
cov_data = pd.read_csv("3-2-3-cov.csv")
cov_data

x   y
0  18.5  34
1  18.7  39
2  19.1  41
3  19.7  38
4  21.5  45
5  21.7  41
6  21.8  52
7  22.0  44
8  23.4  44
9  23.8  49

In [12]:
x = cov_data["x"]
y = cov_data["y"]
N = len(cov_data)

mu_x = np.mean(x)
mu_y = np.mean(y)

cov = np.sum((x-mu_x) * (y - mu_y)) / N
cov

6.906

In [13]:
# 分母为N的协方差矩阵

np.cov(x, y, ddof=0)

array([[ 3.282,  6.906],
       [ 6.906, 25.21 ]])

In [18]:
# 分母为N-1的协方差矩阵

np.cov(x, y, ddof=1)

array([[ 3.646,  7.673],
       [ 7.673, 28.011]])

## 皮尔逊积距相关系数

1. 可以看作将协方差标准化为最大值为1,最小值为-1而得出的
1. 不论分母是N或N-1,皮尔逊积距不变
1. 相关系数接近0时，图形可能是不一样的，可以通过分析图形来获得一些信息

In [20]:
sigma_2_x = np.var(x, ddof=1)
sigma_2_y = np.var(y, ddof=1)
cov = np.sum((x-mu_x) * (y - mu_y)) / (N - 1)
rho = cov / np.sqrt(sigma_2_x * sigma_2_y)
rho

0.759

In [21]:
sigma_2_x = np.var(x, ddof=0)
sigma_2_y = np.var(y, ddof=0)
cov = np.sum((x-mu_x) * (y - mu_y)) / N
rho = cov / np.sqrt(sigma_2_x * sigma_2_y)
rho

0.759

In [22]:
np.corrcoef(x, y)

array([[1.   , 0.759],
       [0.759, 1.   ]])