# Numpy

In [3]:
import numpy as np

# Array

## 基本运算

1. 所有对数组的基本运算都会被施加到每个元素，相当于用了map运算
1. shape属性输出数组的维度数量，相当于len函数

In [4]:
# Array

python_array = [1, 2, 3, 4, 5]

np_array = np.array(python_array)

In [5]:
np_array + 2

array([3, 4, 5, 6, 7])

In [6]:
np_array * 3

array([ 3,  6,  9, 12, 15])

In [7]:
np_array.shape

(5,)

## 生成数组

1. 生成等差数列arange(start, stop, step) **不包含stop数值**
1. 生成指定元素填充的数列tile("A", 5) - ["A", "A", "A", "A", "A"]
1. zeros生成0填充的数列 **数列中元素均为浮点数，不是整数**
1. ones生成1填充的数列 **数列中元素均为浮点数，不是整数**

In [10]:
# 生成等差数列

np.arange(start=0, stop=10, step=2)

array([0, 2, 4, 6, 8])

In [11]:
# 生成指定元素填充的数列

np.tile(0, 4)

array([0, 0, 0, 0])

In [14]:
# 生成0填充的数列

np.zeros([4, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
# 生成1填充的数列

np.ones([4, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 多维数组切片

1. 可以对多维数组切片，语法与python相同

In [16]:
a = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10]])

a[1, 1:3]

array([7, 8])